site_name: HAMRLINC - High-throughput Analysis of Modified RNAs and Long Intergenic Non-Coding RNAs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlist
    - content.tabs.links
    - content.code.annotation
    - conten.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/chosenobih/HAMRLINC/tree/main
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/chosen_obih
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/chosen-obih-50233897/

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - glightbox:

copyright: |
  &copy; 2023 <a href="https://github.com/chosenobih/HAMRLINC/tree/main" target="_blank" rel="noopener">HARMLINC Development Team</a>